version: '3.8'

services:
  restaurant-service:
    build:
      context: .
      dockerfile: apps/restaurant/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - restaurant-db
    environment:
      DATABASE_URL: postgres://postgres:password@restaurant-db:5432/restaurant
    networks:
      - app-network

  restaurant-db:
    image: postgres:15
    container_name: restaurant-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    ports:
      - "5433:5432"
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # New Delivery Service
  delivery-service:
    build:
      context: .
      dockerfile: apps/delivery/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - delivery-db
    environment:
      DATABASE_URL: postgres://postgres:password@delivery-db:5432/delivery
    networks:
      - app-network

  delivery-db:
    image: postgres:15
    container_name: delivery-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery
    ports:
      - "5434:5432" 
    volumes:
      - delivery_db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  restaurant_db_data:
  delivery_db_data:
