version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - restaurant
      - delivery-service
      - order-service
    networks:
      - app-network

  restaurant:
    build:
      context: .
      dockerfile: apps/restaurant/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - restaurant-db
    environment:
      DATABASE_URL: postgres://postgres:password@restaurant-db:5432/restaurant
    networks:
      - app-network

  restaurant-db:
    image: postgres:15
    container_name: restaurant-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    ports:
      - "5433:5432"
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # New Delivery Service
  delivery-service:
    build:
      context: .
      dockerfile: apps/delivery/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - delivery-db
    environment:
      DATABASE_URL: postgres://postgres:password@delivery-db:5432/delivery
    networks:
      - app-network

  delivery-db:
    image: postgres:15
    container_name: delivery-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery
    ports:
      - "5434:5432" 
    volumes:
      - delivery_db_data:/var/lib/postgresql/data
    networks:
      - app-network


  # New Order Service
  order-service:
    build:
      context: .
      dockerfile: apps/order/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - order-db
    environment:
      DATABASE_URL: postgres://postgres:password@order-db:5432/order
    networks:
      - app-network

  order-db:
    image: postgres:15
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order
    ports:
      - "5435:5432" 
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - app-network

# New Auth Service
  auth-service:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3006:3006'
    depends_on:
      - auth-db
    environment:
      DATABASE_URL: postgres://postgres:password@auth-db:5432/auth
    networks:
      - app-network

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    ports:
      - '5436:5432'
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  restaurant_data:
  delivery_data:
  order_data:
  restaurant_db_data:
  delivery_db_data:
  order_db_data:
  auth_db_data:
