apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
      - name: restaurant
        image: food-delivery-system-restaurant:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
spec:
  type: ClusterIP
  selector:
    app: restaurant
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000